/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViveradoisPvRouteImport } from './routes/viveradois-pv'
import { Route as ViveradoisPoRouteImport } from './routes/viveradois-po'
import { Route as PvMda997RouteImport } from './routes/pv-mda-997'
import { Route as PuMda497CddRouteImport } from './routes/pu-mda-497-cdd'
import { Route as PoMda997RouteImport } from './routes/po-mda-997'
import { Route as PoCddRouteImport } from './routes/po-cdd'
import { Route as PaMdaRouteImport } from './routes/pa-mda'
import { Route as MdaPv297RouteImport } from './routes/mda-pv-297'
import { Route as CddPvRouteImport } from './routes/cdd-pv'
import { Route as CddPWebRouteImport } from './routes/cdd-p-web'
import { Route as AcoragemdeseescolherRouteImport } from './routes/acoragemdeseescolher'
import { Route as IndexRouteImport } from './routes/index'

const ViveradoisPvRoute = ViveradoisPvRouteImport.update({
  id: '/viveradois-pv',
  path: '/viveradois-pv',
  getParentRoute: () => rootRouteImport,
} as any)
const ViveradoisPoRoute = ViveradoisPoRouteImport.update({
  id: '/viveradois-po',
  path: '/viveradois-po',
  getParentRoute: () => rootRouteImport,
} as any)
const PvMda997Route = PvMda997RouteImport.update({
  id: '/pv-mda-997',
  path: '/pv-mda-997',
  getParentRoute: () => rootRouteImport,
} as any)
const PuMda497CddRoute = PuMda497CddRouteImport.update({
  id: '/pu-mda-497-cdd',
  path: '/pu-mda-497-cdd',
  getParentRoute: () => rootRouteImport,
} as any)
const PoMda997Route = PoMda997RouteImport.update({
  id: '/po-mda-997',
  path: '/po-mda-997',
  getParentRoute: () => rootRouteImport,
} as any)
const PoCddRoute = PoCddRouteImport.update({
  id: '/po-cdd',
  path: '/po-cdd',
  getParentRoute: () => rootRouteImport,
} as any)
const PaMdaRoute = PaMdaRouteImport.update({
  id: '/pa-mda',
  path: '/pa-mda',
  getParentRoute: () => rootRouteImport,
} as any)
const MdaPv297Route = MdaPv297RouteImport.update({
  id: '/mda-pv-297',
  path: '/mda-pv-297',
  getParentRoute: () => rootRouteImport,
} as any)
const CddPvRoute = CddPvRouteImport.update({
  id: '/cdd-pv',
  path: '/cdd-pv',
  getParentRoute: () => rootRouteImport,
} as any)
const CddPWebRoute = CddPWebRouteImport.update({
  id: '/cdd-p-web',
  path: '/cdd-p-web',
  getParentRoute: () => rootRouteImport,
} as any)
const AcoragemdeseescolherRoute = AcoragemdeseescolherRouteImport.update({
  id: '/acoragemdeseescolher',
  path: '/acoragemdeseescolher',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acoragemdeseescolher': typeof AcoragemdeseescolherRoute
  '/cdd-p-web': typeof CddPWebRoute
  '/cdd-pv': typeof CddPvRoute
  '/mda-pv-297': typeof MdaPv297Route
  '/pa-mda': typeof PaMdaRoute
  '/po-cdd': typeof PoCddRoute
  '/po-mda-997': typeof PoMda997Route
  '/pu-mda-497-cdd': typeof PuMda497CddRoute
  '/pv-mda-997': typeof PvMda997Route
  '/viveradois-po': typeof ViveradoisPoRoute
  '/viveradois-pv': typeof ViveradoisPvRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acoragemdeseescolher': typeof AcoragemdeseescolherRoute
  '/cdd-p-web': typeof CddPWebRoute
  '/cdd-pv': typeof CddPvRoute
  '/mda-pv-297': typeof MdaPv297Route
  '/pa-mda': typeof PaMdaRoute
  '/po-cdd': typeof PoCddRoute
  '/po-mda-997': typeof PoMda997Route
  '/pu-mda-497-cdd': typeof PuMda497CddRoute
  '/pv-mda-997': typeof PvMda997Route
  '/viveradois-po': typeof ViveradoisPoRoute
  '/viveradois-pv': typeof ViveradoisPvRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acoragemdeseescolher': typeof AcoragemdeseescolherRoute
  '/cdd-p-web': typeof CddPWebRoute
  '/cdd-pv': typeof CddPvRoute
  '/mda-pv-297': typeof MdaPv297Route
  '/pa-mda': typeof PaMdaRoute
  '/po-cdd': typeof PoCddRoute
  '/po-mda-997': typeof PoMda997Route
  '/pu-mda-497-cdd': typeof PuMda497CddRoute
  '/pv-mda-997': typeof PvMda997Route
  '/viveradois-po': typeof ViveradoisPoRoute
  '/viveradois-pv': typeof ViveradoisPvRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acoragemdeseescolher'
    | '/cdd-p-web'
    | '/cdd-pv'
    | '/mda-pv-297'
    | '/pa-mda'
    | '/po-cdd'
    | '/po-mda-997'
    | '/pu-mda-497-cdd'
    | '/pv-mda-997'
    | '/viveradois-po'
    | '/viveradois-pv'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acoragemdeseescolher'
    | '/cdd-p-web'
    | '/cdd-pv'
    | '/mda-pv-297'
    | '/pa-mda'
    | '/po-cdd'
    | '/po-mda-997'
    | '/pu-mda-497-cdd'
    | '/pv-mda-997'
    | '/viveradois-po'
    | '/viveradois-pv'
  id:
    | '__root__'
    | '/'
    | '/acoragemdeseescolher'
    | '/cdd-p-web'
    | '/cdd-pv'
    | '/mda-pv-297'
    | '/pa-mda'
    | '/po-cdd'
    | '/po-mda-997'
    | '/pu-mda-497-cdd'
    | '/pv-mda-997'
    | '/viveradois-po'
    | '/viveradois-pv'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcoragemdeseescolherRoute: typeof AcoragemdeseescolherRoute
  CddPWebRoute: typeof CddPWebRoute
  CddPvRoute: typeof CddPvRoute
  MdaPv297Route: typeof MdaPv297Route
  PaMdaRoute: typeof PaMdaRoute
  PoCddRoute: typeof PoCddRoute
  PoMda997Route: typeof PoMda997Route
  PuMda497CddRoute: typeof PuMda497CddRoute
  PvMda997Route: typeof PvMda997Route
  ViveradoisPoRoute: typeof ViveradoisPoRoute
  ViveradoisPvRoute: typeof ViveradoisPvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viveradois-pv': {
      id: '/viveradois-pv'
      path: '/viveradois-pv'
      fullPath: '/viveradois-pv'
      preLoaderRoute: typeof ViveradoisPvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viveradois-po': {
      id: '/viveradois-po'
      path: '/viveradois-po'
      fullPath: '/viveradois-po'
      preLoaderRoute: typeof ViveradoisPoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pv-mda-997': {
      id: '/pv-mda-997'
      path: '/pv-mda-997'
      fullPath: '/pv-mda-997'
      preLoaderRoute: typeof PvMda997RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pu-mda-497-cdd': {
      id: '/pu-mda-497-cdd'
      path: '/pu-mda-497-cdd'
      fullPath: '/pu-mda-497-cdd'
      preLoaderRoute: typeof PuMda497CddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/po-mda-997': {
      id: '/po-mda-997'
      path: '/po-mda-997'
      fullPath: '/po-mda-997'
      preLoaderRoute: typeof PoMda997RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/po-cdd': {
      id: '/po-cdd'
      path: '/po-cdd'
      fullPath: '/po-cdd'
      preLoaderRoute: typeof PoCddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pa-mda': {
      id: '/pa-mda'
      path: '/pa-mda'
      fullPath: '/pa-mda'
      preLoaderRoute: typeof PaMdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mda-pv-297': {
      id: '/mda-pv-297'
      path: '/mda-pv-297'
      fullPath: '/mda-pv-297'
      preLoaderRoute: typeof MdaPv297RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cdd-pv': {
      id: '/cdd-pv'
      path: '/cdd-pv'
      fullPath: '/cdd-pv'
      preLoaderRoute: typeof CddPvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cdd-p-web': {
      id: '/cdd-p-web'
      path: '/cdd-p-web'
      fullPath: '/cdd-p-web'
      preLoaderRoute: typeof CddPWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acoragemdeseescolher': {
      id: '/acoragemdeseescolher'
      path: '/acoragemdeseescolher'
      fullPath: '/acoragemdeseescolher'
      preLoaderRoute: typeof AcoragemdeseescolherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcoragemdeseescolherRoute: AcoragemdeseescolherRoute,
  CddPWebRoute: CddPWebRoute,
  CddPvRoute: CddPvRoute,
  MdaPv297Route: MdaPv297Route,
  PaMdaRoute: PaMdaRoute,
  PoCddRoute: PoCddRoute,
  PoMda997Route: PoMda997Route,
  PuMda497CddRoute: PuMda497CddRoute,
  PvMda997Route: PvMda997Route,
  ViveradoisPoRoute: ViveradoisPoRoute,
  ViveradoisPvRoute: ViveradoisPvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
