/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViveradoisPvRouteImport } from './routes/viveradois-pv'
import { Route as ViveradoisPoRouteImport } from './routes/viveradois-po'
import { Route as MdaPv297RouteImport } from './routes/mda-pv-297'
import { Route as CddPvRouteImport } from './routes/cdd-pv'
import { Route as CddPWebRouteImport } from './routes/cdd-p-web'
import { Route as IndexRouteImport } from './routes/index'

const ViveradoisPvRoute = ViveradoisPvRouteImport.update({
  id: '/viveradois-pv',
  path: '/viveradois-pv',
  getParentRoute: () => rootRouteImport,
} as any)
const ViveradoisPoRoute = ViveradoisPoRouteImport.update({
  id: '/viveradois-po',
  path: '/viveradois-po',
  getParentRoute: () => rootRouteImport,
} as any)
const MdaPv297Route = MdaPv297RouteImport.update({
  id: '/mda-pv-297',
  path: '/mda-pv-297',
  getParentRoute: () => rootRouteImport,
} as any)
const CddPvRoute = CddPvRouteImport.update({
  id: '/cdd-pv',
  path: '/cdd-pv',
  getParentRoute: () => rootRouteImport,
} as any)
const CddPWebRoute = CddPWebRouteImport.update({
  id: '/cdd-p-web',
  path: '/cdd-p-web',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cdd-p-web': typeof CddPWebRoute
  '/cdd-pv': typeof CddPvRoute
  '/mda-pv-297': typeof MdaPv297Route
  '/viveradois-po': typeof ViveradoisPoRoute
  '/viveradois-pv': typeof ViveradoisPvRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cdd-p-web': typeof CddPWebRoute
  '/cdd-pv': typeof CddPvRoute
  '/mda-pv-297': typeof MdaPv297Route
  '/viveradois-po': typeof ViveradoisPoRoute
  '/viveradois-pv': typeof ViveradoisPvRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cdd-p-web': typeof CddPWebRoute
  '/cdd-pv': typeof CddPvRoute
  '/mda-pv-297': typeof MdaPv297Route
  '/viveradois-po': typeof ViveradoisPoRoute
  '/viveradois-pv': typeof ViveradoisPvRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cdd-p-web'
    | '/cdd-pv'
    | '/mda-pv-297'
    | '/viveradois-po'
    | '/viveradois-pv'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cdd-p-web'
    | '/cdd-pv'
    | '/mda-pv-297'
    | '/viveradois-po'
    | '/viveradois-pv'
  id:
    | '__root__'
    | '/'
    | '/cdd-p-web'
    | '/cdd-pv'
    | '/mda-pv-297'
    | '/viveradois-po'
    | '/viveradois-pv'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CddPWebRoute: typeof CddPWebRoute
  CddPvRoute: typeof CddPvRoute
  MdaPv297Route: typeof MdaPv297Route
  ViveradoisPoRoute: typeof ViveradoisPoRoute
  ViveradoisPvRoute: typeof ViveradoisPvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viveradois-pv': {
      id: '/viveradois-pv'
      path: '/viveradois-pv'
      fullPath: '/viveradois-pv'
      preLoaderRoute: typeof ViveradoisPvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viveradois-po': {
      id: '/viveradois-po'
      path: '/viveradois-po'
      fullPath: '/viveradois-po'
      preLoaderRoute: typeof ViveradoisPoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mda-pv-297': {
      id: '/mda-pv-297'
      path: '/mda-pv-297'
      fullPath: '/mda-pv-297'
      preLoaderRoute: typeof MdaPv297RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cdd-pv': {
      id: '/cdd-pv'
      path: '/cdd-pv'
      fullPath: '/cdd-pv'
      preLoaderRoute: typeof CddPvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cdd-p-web': {
      id: '/cdd-p-web'
      path: '/cdd-p-web'
      fullPath: '/cdd-p-web'
      preLoaderRoute: typeof CddPWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CddPWebRoute: CddPWebRoute,
  CddPvRoute: CddPvRoute,
  MdaPv297Route: MdaPv297Route,
  ViveradoisPoRoute: ViveradoisPoRoute,
  ViveradoisPvRoute: ViveradoisPvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
